In [1]:
#Import Dependencies

import pandas as pd
import numpy as np
from datetime import datetime
import sqlalchemy
import requests
import json

from config import gkey

In [2]:
#Read in csvs

players = pd.read_csv('players.csv')
salaries = pd.read_csv('salaries.csv')

In [3]:
#Merge Players and Salaries on (_id and player_id)

players = pd.merge(players, salaries, left_on = '_id', right_on = 'player_id')

In [4]:
#Choose an appropriate format for useful fields

players['draft_year'] = players['draft_year'].astype(float)
players['position'] = players['position'].astype(str)
players['player_id'] = players['player_id'].astype(str)
players['college'] = players['college'].astype(str)

In [5]:
#limit data to 2000 and beyond

players = players[players.draft_year >= 2000]

In [6]:
# Select columns for dataframe

players_cols = ['player_id','birthDate','draft_year','name','position',
                'college','salary','season_end','season_start','team']

In [7]:
# Applied to dataframe

players = players[players_cols]

In [8]:
players.dtypes

player_id        object
birthDate        object
draft_year      float64
name             object
position         object
college          object
salary            int64
season_end        int64
season_start      int64
team             object
dtype: object

In [9]:
#Find max salary by id and save to idx

idx = players.groupby(['player_id'])['salary'].transform(max) == players['salary']

In [10]:
# Applied idx to dataframe

players = players[idx]
players.reset_index()

,index,player_id,birthDate,draft_year,name,position,college,salary,season_end,season_start,team
0,39,abrinal01,"August 1, 1993",2013.0,Alex Abrines,Shooting Guard,nan,5994764,2017,2016,Oklahoma City Thunder
1,42,ackeral01,"January 21, 1983",2005.0,Alex Acker,Shooting Guard,Pepperdine University,839209,2007,2006,Detroit Pistons
2,53,acyqu01,"October 6, 1990",2012.0,Quincy Acy,Power Forward and Small Forward,Baylor University,1914544,2017,2016,Brooklyn Nets
3,59,adamsha01,"June 20, 1984",2006.0,Hassan Adams,Shooting Guard,University of Arizona,412718,2007,2006,New Jersey Nets
4,63,adamsjo01,"July 8, 1994",2014.0,Jordan Adams,Shooting Guard,"University of California, Los Angeles",1465080,2017,2016,Memphis Grizzlies
...,...,...,...,...,...,...,...,...,...,...,...
978,14147,zellety01,"January 17, 1990",2012.0,Tyler Zeller,Center,University of North Carolina,8000000,2017,2016,Boston Celtics
979,14157,zimmest01,"September 9, 1996",2016.0,Stephen Zimmerman,Center,"University of Nevada, Las Vegas",950000,2017,2016,Orlando Magic
980,14159,zipsepa01,"February 18, 1994",2016.0,Paul Zipser,Small Forward,nan,1312611,2018,2017,Chicago Bulls
981,14160,zizican01,"January 4, 1997",2016.0,Ante Zizic,Center,nan,1645200,2018,2017,Cleveland Cavaliers
982,14162,zubaciv01,"March 18, 1997",2016.0,Ivica Zubac,Center,nan,1312611,2018,2017,Los Angeles Lakers

In [11]:
players[50:100]

,player_id,birthDate,draft_year,name,position,college,salary,season_end,season_start,team
713,balllo01,"October 27, 1997",2017.0,Lonzo Ball,Point Guard,"University of California, Los Angeles",6286560,2018,2017,Los Angeles Lakers
725,banksma01,"November 19, 1981",2003.0,Marcus Banks,Point Guard,"University of Nevada, Las Vegas",4847586,2011,2010,New Orleans Hornets
738,barbole01,"November 28, 1982",2003.0,Leandro Barbosa,Point Guard and Shooting Guard,nan,7600000,2012,2011,Toronto Raptors
765,bargnan01,"October 26, 1985",2006.0,Andrea Bargnani,Power Forward and Center,nan,11862500,2014,2013,New York Knicks
784,barkler01,"February 21, 1978",2000.0,Erick Barkley,Point Guard,St. John's University,712200,2001,2000,Portland Trail Blazers
792,barneha02,"May 30, 1992",2012.0,Harrison Barnes,Power Forward and Small Forward,University of North Carolina,23112004,2018,2017,Dallas Mavericks
806,barnema02,"March 9, 1980",2002.0,Matt Barnes,Small Forward and Power Forward,"University of California, Los Angeles",6125000,2017,2016,Sacramento Kings
865,bartowi01,"January 6, 1991",2012.0,Will Barton,Shooting Guard,University of Memphis,3533333,2017,2016,Denver Nuggets
866,bartowi01,"January 6, 1991",2012.0,Will Barton,Shooting Guard,University of Memphis,3533333,2018,2017,Denver Nuggets
877,bassbr01,"April 30, 1985",2005.0,Brandon Bass,Power Forward and Center,Louisiana State University,6900000,2015,2014,Boston Celtics
914,battish01,"September 9, 1978",2001.0,Shane Battier,Small Forward and Shooting Guard,Duke University,7354500,2011,2010,Memphis Grizzlies
937,batumni01,"December 14, 1988",2008.0,Nicolas Batum,Small Forward and Shooting Guard,nan,22434783,2018,2017,Charlotte Hornets
941,baxtelo01,"January 27, 1979",2002.0,Lonny Baxter,Power Forward and Center,University of Maryland,745248,2006,2005,Houston Rockets
950,bayleje01,"August 20, 1988",2008.0,Jerryd Bayless,Point Guard and Shooting Guard,University of Arizona,9424084,2017,2016,Philadelphia 76ers
970,bealbr01,"June 28, 1993",2012.0,Bradley Beal,Shooting Guard,University of Florida,23775506,2018,2017,Washington Wizards
972,beaslje01,"May 17, 1980",2003.0,Jerome Beasley,Power Forward,"Midland College, University of North Dakota",620046,2005,2004,Miami Heat
974,beaslma01,"November 26, 1996",2016.0,Malik Beasley,Shooting Guard,Florida State University,1700640,2018,2017,Denver Nuggets
978,beaslmi01,"January 9, 1989",2008.0,Michael Beasley,Power Forward and Small Forward,Kansas State University,6262347,2012,2011,Minnesota Timberwolves
991,beaubro01,"February 24, 1988",2009.0,Rodrigue Beaubois,Point Guard,nan,2227333,2013,2012,Dallas Mavericks
1007,belinma01,"March 25, 1986",2007.0,Marco Belinelli,Shooting Guard and Small Forward,nan,6333333,2016,2015,Sacramento Kings
1008,belinma01,"March 25, 1986",2007.0,Marco Belinelli,Shooting Guard and Small Forward,nan,6333333,2017,2016,Charlotte Hornets
1019,belljo01,"January 7, 1995",2017.0,Jordan Bell,Center,University of Oregon,815615,2018,2017,Golden State Warriors
1034,belltr01,"November 10, 1980",2003.0,Troy Bell,Point Guard,Boston College,1478280,2006,2005,Memphis Grizzlies
1036,bembrde01,"July 4, 1994",2016.0,DeAndre' Bembry,Shooting Guard and Small Forward,Saint Joseph's University,1567200,2018,2017,Atlanta Hawks
1038,bendedr01,"November 17, 1997",2016.0,Dragan Bender,Power Forward,nan,4468800,2018,2017,Phoenix Suns
1064,bennean01,"March 14, 1993",2013.0,Anthony Bennett,Power Forward,"University of Nevada, Las Vegas",5563920,2015,2014,Minnesota Timberwolves
1085,bensoke02,"August 13, 1988",2011.0,Keith Benson,Center,Oakland University,75000,2017,2016,Miami Heat
1090,bentibe01,"March 29, 1995",2016.0,Ben Bentil,Power Forward,Providence College,250000,2017,2016,Boston Celtics
1097,bertada01,"November 12, 1992",2011.0,Davis Bertans,Power Forward,nan,1312611,2018,2017,San Antonio Spurs
1111,beverpa01,"July 12, 1988",2009.0,Patrick Beverley,Point Guard and Shooting Guard,University of Arkansas,6500000,2016,2015,Houston Rockets
1133,biedran01,"April 2, 1986",2004.0,Andris Biedrins,Center,nan,9000000,2009,2008,Golden State Warriors
1134,biedran01,"April 2, 1986",2004.0,Andris Biedrins,Center,nan,9000000,2010,2009,Golden State Warriors
1135,biedran01,"April 2, 1986",2004.0,Andris Biedrins,Center,nan,9000000,2011,2010,Golden State Warriors
1136,biedran01,"April 2, 1986",2004.0,Andris Biedrins,Center,nan,9000000,2012,2011,Golden State Warriors
1137,biedran01,"April 2, 1986",2004.0,Andris Biedrins,Center,nan,9000000,2013,2012,Golden State Warriors
1138,biedran01,"April 2, 1986",2004.0,Andris Biedrins,Center,nan,9000000,2014,2013,Utah Jazz
1176,biyombi01,"August 28, 1992",2011.0,Bismack Biyombo,Center,nan,17000000,2017,2016,Orlando Magic
1177,biyombi01,"August 28, 1992",2011.0,Bismack Biyombo,Center,nan,17000000,2018,2017,Orlando Magic
1178,bjeline01,"May 9, 1988",2010.0,Nemanja Bjelica,Power Forward,nan,4000000,2016,2015,Minnesota Timberwolves
1204,blairde01,"April 22, 1989",2009.0,DeJuan Blair,Center and Power Forward,University of Pittsburgh,2000000,2015,2014,Washington Wizards
1205,blairde01,"April 22, 1989",2009.0,DeJuan Blair,Center and Power Forward,University of Pittsburgh,2000000,2016,2015,Phoenix Suns
1212,blakest01,"February 26, 1980",2003.0,Steve Blake,Point Guard,University of Maryland,4930000,2010,2009,Los Angeles Clippers
1219,blalowi01,"September 8, 1983",2006.0,Will Blalock,Point Guard,Iowa State University,412718,2007,2006,Detroit Pistons
1234,blatcan01,"August 22, 1986",2005.0,Andray Blatche,Center and Power Forward,nan,8471339,2015,2014,Washington Wizards
1254,bledser01,"December 9, 1989",2010.0,Eric Bledsoe,Point Guard,University of Kentucky,14500000,2018,2017,Milwaukee Bucks
1288,boganke01,"May 12, 1980",2003.0,Keith Bogans,Small Forward and Shooting Guard,University of Kentucky,5058198,2014,2013,Boston Celtics
1289,bogdabo01,"August 18, 1992",2014.0,Bogdan Bogdanovic,Shooting Guard,nan,9470614,2018,2017,Sacramento Kings
1293,bogdabo02,"April 18, 1989",2011.0,Bojan Bogdanovic,Small Forward,nan,10500000,2018,2017,Indiana Pacers
1318,bogutan01,"November 28, 1984",2005.0,Andrew Bogut,Power Forward and Center,University of Utah,14000000,2014,2013,Golden State Warriors
1351,bonnema01,"April 5, 1980",2003.0,Matt Bonner,Power Forward and Center,University of Florida,3945000,2014,2013,San Antonio Spurs

In [15]:
unique_college= []
for college1 in players.college:
    college1 = college1.split(",")
    if len(college1) > 1:
        college_new = college1[1]
        if len(college_new) > 1:
             print(college_new)
    else:
        college_new = college1[0]
    
    unique_college.append(college_new)

 Los Angeles
 Los Angeles
 California State University
 Oklahoma State University
 Los Angeles
 Los Angeles
 Los Angeles
 Reno
 Los Angeles
 Las Vegas
 Los Angeles
 University of North Dakota
 Las Vegas
 Villanova University
 University of Texas at El Paso
 University of Missouri
 University of Missouri
 Georgia Institute of Technology
 Los Angeles
 Xavier University
 Gonzaga University
 University of Idaho
 University of Houston
 Florida State University
 Fresno
 Long Beach
 Los Angeles
 Reno
 Manhattan College
 Los Angeles
 Syracuse University
 Fresno
 University of New Mexico
 Oklahoma State University
 University of New Mexico
 University of Louisiana at Lafayette
 Louisiana State University
 Brigham Young University
 University of Georgia
 Fresno
 Los Angeles
 Los Angeles
 Los Angeles
 Duke University
 University of Notre Dame
 California State University
 Reno
 University of California
 Syracuse University
 Duke University
 Los Angeles
 Los Angeles
 Los Angeles
 Los Angeles
 Los Angeles
 Los Angeles
 University of Florida
 Fresno
 Los Angeles
 Las Vegas
 Reno
 California State University
 Los Angeles
 Mississippi State University
 Los Angeles
 Shaw University
 Iowa State University
 University of Texas at Austin
 Los Angeles
 Mississippi State University
 Reno
 University of Alabama at Birmingham
 Reno
 Fullerton
 Los Angeles
 Baylor University
 Las Vegas
 Los Angeles
 Los Angeles
 University of Cincinnati
 University of Cincinnati
 University of Memphis
 University of Arizona
 University of Oregon
 Las Vegas

In [16]:
players['college'] = unique_college
merged_duplicates = players[players.duplicated()]
print("Duplicate Rows except first occurrence based on all columns are :")
print(merged_duplicates)

# Select duplicate rows except first occurrence based on all columns
merged_duplicates = players[players.duplicated()]

Duplicate Rows except first occurrence based on all columns are :
Empty DataFrame
Columns: [player_id, birthDate, draft_year, name, position, college, salary, season_end, season_start, team]
Index: []

In [17]:
players['college'] = players['college'].str.replace('Los Angeles','University of California')
players['college'] = players['college'].str.replace('Fresno','University of California')
players['college'] = players['college'].str.replace('Long Beach','University of California')
players['college'] = players['college'].str.replace('Fullerton','University of California')
players['college'] = players['college'].str.replace('Reno','University of Nevada')
players['college'] = players['college'].str.replace('Las Vegas','University of Nevada')
players['college'] = players['college'].str.replace('nan','')

In [18]:
players.drop(players.loc[players["college"] == ""].index, inplace=True)

In [19]:
players = players.dropna(subset=['college'])
players.head(1000)

,player_id,birthDate,draft_year,name,position,college,salary,season_end,season_start,team
42,ackeral01,"January 21, 1983",2005.0,Alex Acker,Shooting Guard,Pepperdine University,839209,2007,2006,Detroit Pistons
53,acyqu01,"October 6, 1990",2012.0,Quincy Acy,Power Forward and Small Forward,Baylor University,1914544,2017,2016,Brooklyn Nets
59,adamsha01,"June 20, 1984",2006.0,Hassan Adams,Shooting Guard,University of Arizona,412718,2007,2006,New Jersey Nets
63,adamsjo01,"July 8, 1994",2014.0,Jordan Adams,Shooting Guard,University of California,1465080,2017,2016,Memphis Grizzlies
76,adamsst01,"July 20, 1993",2013.0,Steven Adams,Center,University of Pittsburgh,22471910,2018,2017,Oklahoma City Thunder
...,...,...,...,...,...,...,...,...,...,...
14122,youngsa01,"June 1, 1985",2009.0,Sam Young,Shooting Guard and Small Forward,University of Pittsburgh,947800,2012,2011,Memphis Grizzlies
14134,youngth01,"June 21, 1988",2007.0,Thaddeus Young,Power Forward,Georgia Institute of Technology,14796348,2018,2017,Indiana Pacers
14141,zelleco01,"October 5, 1992",2013.0,Cody Zeller,Center,Indiana University,12584270,2018,2017,Charlotte Hornets
14147,zellety01,"January 17, 1990",2012.0,Tyler Zeller,Center,University of North Carolina,8000000,2017,2016,Boston Celtics
14157,zimmest01,"September 9, 1996",2016.0,Stephen Zimmerman,Center,University of Nevada,950000,2017,2016,Orlando Magic

In [20]:
NBADF = pd.DataFrame(players)
NBADF['college']

42                 Pepperdine University
53                     Baylor University
59                 University of Arizona
63              University of California
76              University of Pittsburgh
                      ...
14122           University of Pittsburgh
14134    Georgia Institute of Technology
14141                 Indiana University
14147       University of North Carolina
14157               University of Nevada
Name: college, Length: 762, dtype: object

In [21]:
NBADF['college'][50:100]

950                          University of Arizona
970                          University of Florida
972                     University of North Dakota
974                       Florida State University
978                        Kansas State University
1019                          University of Oregon
1034                                Boston College
1036                     Saint Joseph's University
1064                          University of Nevada
1085                            Oakland University
1090                            Providence College
1111                        University of Arkansas
1204                      University of Pittsburgh
1205                      University of Pittsburgh
1212                        University of Maryland
1219                         Iowa State University
1254                        University of Kentucky
1288                        University of Kentucky
1318                            University of Utah
1351                         University of Florida
1356                        University of Kentucky
1363                            Clemson University
1369                     University of Connecticut
1396                               Duke University
1402                           Stanford University
1418               Georgia Institute of Technology
1422                         Georgetown University
1482                         Iowa State University
1490                 University of Texas at Austin
1496                          Villanova University
1513                  University of North Carolina
1572                         University of Florida
1579                             Auburn University
1584                        University of Arkansas
1609                      University of Washington
1610                      University of Washington
1611                      University of Washington
1613                        University of Virginia
1619                          University of Oregon
1625                          University of Oregon
1632                            Providence College
1659                           Syracuse University
1672    University of Illinois at Urbana-Champaign
1677                             Xavier University
1687                Indian Hills Community College
1692                      University of California
1696             Okaloosa-Walton Community College
1755                     Michigan State University
1756                     Michigan State University
1757                     Michigan State University
Name: college, dtype: object

In [22]:
NBADF.head(1000)

,player_id,birthDate,draft_year,name,position,college,salary,season_end,season_start,team
42,ackeral01,"January 21, 1983",2005.0,Alex Acker,Shooting Guard,Pepperdine University,839209,2007,2006,Detroit Pistons
53,acyqu01,"October 6, 1990",2012.0,Quincy Acy,Power Forward and Small Forward,Baylor University,1914544,2017,2016,Brooklyn Nets
59,adamsha01,"June 20, 1984",2006.0,Hassan Adams,Shooting Guard,University of Arizona,412718,2007,2006,New Jersey Nets
63,adamsjo01,"July 8, 1994",2014.0,Jordan Adams,Shooting Guard,University of California,1465080,2017,2016,Memphis Grizzlies
76,adamsst01,"July 20, 1993",2013.0,Steven Adams,Center,University of Pittsburgh,22471910,2018,2017,Oklahoma City Thunder
...,...,...,...,...,...,...,...,...,...,...
14122,youngsa01,"June 1, 1985",2009.0,Sam Young,Shooting Guard and Small Forward,University of Pittsburgh,947800,2012,2011,Memphis Grizzlies
14134,youngth01,"June 21, 1988",2007.0,Thaddeus Young,Power Forward,Georgia Institute of Technology,14796348,2018,2017,Indiana Pacers
14141,zelleco01,"October 5, 1992",2013.0,Cody Zeller,Center,Indiana University,12584270,2018,2017,Charlotte Hornets
14147,zellety01,"January 17, 1990",2012.0,Tyler Zeller,Center,University of North Carolina,8000000,2017,2016,Boston Celtics
14157,zimmest01,"September 9, 1996",2016.0,Stephen Zimmerman,Center,University of Nevada,950000,2017,2016,Orlando Magic

In [23]:
#list of colleges
colleges = NBADF["college"]

# Build the endpoint URL
NewDF = pd.DataFrame()
for college in colleges:
    target_url = ('https://maps.googleapis.com/maps/api/geocode/json?'
    'address={0}&key={1}').format(college, gkey)
    geo_data = requests.get(target_url).json()
    lat = geo_data["results"][0]["geometry"]["location"]["lat"]
    lng = geo_data["results"][0]["geometry"]["location"]["lng"]
    coll_coord = {"college": college, "lat": lat, "long": lng}
    print(coll_coord)
    NewDF = NewDF.append(coll_coord, ignore_index=True)

{'college': 'Pepperdine University', 'lat': 34.0414045, 'long': -118.7095814}
{'college': 'Baylor University', 'lat': 31.5469132, 'long': -97.1210998}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Pittsburgh', 'lat': 40.4443533, 'long': -79.960835}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'Florida State University', 'lat': 30.4418778, 'long': -84.2984889}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': ' California State University', 'lat': 34.0667698, 'long': -118.1684392}
{'college': 'West Virginia University', 'lat': 39.6480359, 'long': -79.9697147}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'Temple University', 'lat': 39.9805942, 'long': -75.1557376}
{'college': ' Oklahoma State University', 'lat': 36.1270236, 'long': -97.07372219999999}
{'college': 'Rice University', 'lat': 29.7173941, 'long': -95.40183119999999}
{'college': 'Wake Forest University', 'lat': 36.1355052, 'long': -80.2791958}
{'college': 'Oklahoma State University', 'lat': 36.1270236, 'long': -97.07372219999999}
{'college': 'University of Virginia', 'lat': 38.0335529, 'long': -78.5079772}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'Indiana University', 'lat': 39.1754487, 'long': -86.512627}
{'college': 'Brigham Young University', 'lat': 40.2518435, 'long': -111.6493156}
{'college': 'University of Illinois at Urbana-Champaign', 'lat': 40.1019523, 'long': -88.2271615}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Pepperdine University', 'lat': 34.0414045, 'long': -118.7095814}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'University of Illinois at Urbana-Champaign', 'lat': 40.1019523, 'long': -88.2271615}
{'college': 'Arizona State University', 'lat': 33.4242399, 'long': -111.9280527}
{'college': ' University of Nevada', 'lat': 39.5441917, 'long': -119.816397}
{'college': 'Florida State University', 'lat': 30.4418778, 'long': -84.2984889}
{'college': 'University of New Mexico', 'lat': 35.0843187, 'long': -106.6197812}
{'college': 'University of South Carolina', 'lat': 33.9937575, 'long': -81.0299186}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': ' University of Nevada', 'lat': 39.5441917, 'long': -119.816397}
{'college': "St. John's University", 'lat': 40.7220627, 'long': -73.79421119999999}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Memphis', 'lat': 35.1187498, 'long': -89.9374928}
{'college': 'University of Memphis', 'lat': 35.1187498, 'long': -89.9374928}
{'college': 'Louisiana State University', 'lat': 30.4132579, 'long': -91.1800023}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Maryland', 'lat': 38.9869183, 'long': -76.9425543}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': ' University of North Dakota', 'lat': 47.922891, 'long': -97.0768014}
{'college': 'Florida State University', 'lat': 30.4418778, 'long': -84.2984889}
{'college': 'Kansas State University', 'lat': 39.1974437, 'long': -96.5847249}
{'college': 'University of Oregon', 'lat': 44.0448302, 'long': -123.0726055}
{'college': 'Boston College', 'lat': 42.3355488, 'long': -71.16849450000001}
{'college': "Saint Joseph's University", 'lat': 39.9951217, 'long': -75.23993279999999}
{'college': ' University of Nevada', 'lat': 39.5441917, 'long': -119.816397}
{'college': 'Oakland University', 'lat': 42.6679486, 'long': -83.2081632}
{'college': 'Providence College', 'lat': 41.8440925, 'long': -71.4381653}
{'college': 'University of Arkansas', 'lat': 36.0686895, 'long': -94.1748471}
{'college': 'University of Pittsburgh', 'lat': 40.4443533, 'long': -79.960835}
{'college': 'University of Pittsburgh', 'lat': 40.4443533, 'long': -79.960835}
{'college': 'University of Maryland', 'lat': 38.9869183, 'long': -76.9425543}
{'college': 'Iowa State University', 'lat': 42.0266187, 'long': -93.6464654}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Utah', 'lat': 40.7649368, 'long': -111.8421021}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Clemson University', 'lat': 34.6738437, 'long': -82.8368654}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Stanford University', 'lat': 37.4274745, 'long': -122.169719}
{'college': 'Georgia Institute of Technology', 'lat': 33.7756178, 'long': -84.39628499999999}
{'college': 'Georgetown University', 'lat': 38.9076089, 'long': -77.07225849999999}
{'college': 'Iowa State University', 'lat': 42.0266187, 'long': -93.6464654}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': ' Villanova University', 'lat': 40.0378952, 'long': -75.34333149999999}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': 'Auburn University', 'lat': 32.5933574, 'long': -85.4951663}
{'college': 'University of Arkansas', 'lat': 36.0686895, 'long': -94.1748471}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': 'University of Virginia', 'lat': 38.0335529, 'long': -78.5079772}
{'college': 'University of Oregon', 'lat': 44.0448302, 'long': -123.0726055}
{'college': 'University of Oregon', 'lat': 44.0448302, 'long': -123.0726055}
{'college': 'Providence College', 'lat': 41.8440925, 'long': -71.4381653}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'University of Illinois at Urbana-Champaign', 'lat': 40.1019523, 'long': -88.2271615}
{'college': 'Xavier University', 'lat': 39.149448, 'long': -84.47363740000002}
{'college': 'Indian Hills Community College', 'lat': 41.044962, 'long': -92.394464}
{'college': 'University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Okaloosa-Walton Community College', 'lat': 30.5394163, 'long': -86.475644}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'Southern Methodist University', 'lat': 32.8412178, 'long': -96.78451749999999}
{'college': 'Indiana University', 'lat': 39.1754487, 'long': -86.512627}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}

{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'University of Michigan', 'lat': 42.2780436, 'long': -83.7382241}
{'college': 'University of Colorado', 'lat': 40.00758099999999, 'long': -105.2659417}
{'college': 'University of Memphis', 'lat': 35.1187498, 'long': -89.9374928}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'Marquette University', 'lat': 43.0388337, 'long': -87.92856669999999}
{'college': 'La Salle University', 'lat': 40.0386037, 'long': -75.1566354}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': 'University of Georgia', 'lat': 33.9480053, 'long': -83.3773221}
{'college': 'Murray State University', 'lat': 36.6163842, 'long': -88.3214979}
{'college': ' University of Texas at El Paso', 'lat': 31.7709368, 'long': -106.5046405}
{'college': 'Purdue University', 'lat': 40.4237054, 'long': -86.92119459999999}
{'college': 'University of Memphis', 'lat': 35.1187498, 'long': -89.9374928}
{'college': ' University of Missouri', 'lat': 38.9403808, 'long': -92.32773750000001}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Xavier University', 'lat': 39.149448, 'long': -84.47363740000002}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'DePaul University', 'lat': 41.9247559, 'long': -87.6566465}
{'college': 'Stanford University', 'lat': 37.4274745, 'long': -122.169719}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'Xavier University', 'lat': 39.149448, 'long': -84.47363740000002}
{'college': 'University of Louisville', 'lat': 38.2122761, 'long': -85.75850229999999}
{'college': ' University of Missouri', 'lat': 38.9403808, 'long': -92.32773750000001}
{'college': 'Hofstra University', 'lat': 40.7166872, 'long': -73.5993965}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'Cleveland State University', 'lat': 41.5025072, 'long': -81.6746268}
{'college': ' Georgia Institute of Technology', 'lat': 33.7756178, 'long': -84.39628499999999}
{'college': 'Stanford University', 'lat': 37.4274745, 'long': -122.169719}
{'college': 'Stanford University', 'lat': 37.4274745, 'long': -122.169719}
{'college': 'Wake Forest University', 'lat': 36.1355052, 'long': -80.2791958}
{'college': 'Temple University', 'lat': 39.9805942, 'long': -75.1557376}
{'college': 'Gonzaga University', 'lat': 47.66703210000001, 'long': -117.4014343}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'Ohio State University', 'lat': 40.0068363, 'long': -83.0306222}
{'college': 'University of Notre Dame', 'lat': 41.7055716, 'long': -86.2353388}
{'college': 'University of Illinois at Urbana-Champaign', 'lat': 40.1019523, 'long': -88.2271615}
{'college': 'University of Illinois at Urbana-Champaign', 'lat': 40.1019523, 'long': -88.2271615}
{'college': 'University of Illinois at Urbana-Champaign', 'lat': 40.1019523, 'long': -88.2271615}
{'college': 'Ohio State University', 'lat': 40.0068363, 'long': -83.0306222}
{'college': "St. John's University", 'lat': 40.7220627, 'long': -73.79421119999999}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Michigan', 'lat': 42.2780436, 'long': -83.7382241}
{'college': ' Xavier University', 'lat': 39.149448, 'long': -84.47363740000002}
{'college': 'Georgia Institute of Technology', 'lat': 33.7756178, 'long': -84.39628499999999}
{'college': 'Marquette University', 'lat': 43.0388337, 'long': -87.92856669999999}
{'college': 'Villanova University', 'lat': 40.0378952, 'long': -75.34333149999999}
{'college': 'Oregon State University', 'lat': 44.5637806, 'long': -123.2794443}
{'college': 'Oklahoma State University', 'lat': 36.1270236, 'long': -97.07372219999999}
{'college': 'Davidson College', 'lat': 35.5008018, 'long': -80.8446725}
{'college': 'Seton Hall University', 'lat': 40.7433773, 'long': -74.2465446}
{'college': 'University of Alabama', 'lat': 33.2140233, 'long': -87.5391418}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'Louisiana State University', 'lat': 30.4132579, 'long': -91.1800023}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'Gonzaga University', 'lat': 47.66703210000001, 'long': -117.4014343}
{'college': 'University of Wisconsin', 'lat': 43.076592, 'long': -89.4124875}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Southern California', 'lat': 34.0223519, 'long': -118.285117}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Miami', 'lat': 25.7178924, 'long': -80.2746368}
{'college': ' Gonzaga University', 'lat': 47.66703210000001, 'long': -117.4014343}
{'college': ' University of Idaho', 'lat': 46.7288124, 'long': -117.0126084}
{'college': 'Marquette University', 'lat': 43.0388337, 'long': -87.92856669999999}
{'college': 'University of Louisville', 'lat': 38.2122761, 'long': -85.75850229999999}
{'college': 'University of Colorado', 'lat': 40.00758099999999, 'long': -105.2659417}
{'college': 'Arizona State University', 'lat': 33.4242399, 'long': -111.9280527}
{'college': 'University of Maryland', 'lat': 38.9869183, 'long': -76.9425543}
{'college': 'University of Maryland', 'lat': 38.9869183, 'long': -76.9425543}
{'college': 'University of Missouri', 'lat': 38.9403808, 'long': -92.32773750000001}
{'college': 'University of Memphis', 'lat': 35.1187498, 'long': -89.9374928}
{'college': 'University of Oregon', 'lat': 44.0448302, 'long': -123.0726055}
{'college': ' University of Houston', 'lat': 29.7199489, 'long': -95.3422334}
{'college': 'Rutgers University', 'lat': 40.5008186, 'long': -74.44739910000001}
{'college': ' Florida State University', 'lat': 30.4418778, 'long': -84.2984889}
{'college': 'University of Memphis', 'lat': 35.1187498, 'long': -89.9374928}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'Boston College', 'lat': 42.3355488, 'long': -71.16849450000001}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Providence College', 'lat': 41.8440925, 'long': -71.4381653}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'Wichita State University', 'lat': 37.7186367, 'long': -97.29414140000002}
{'college': 'West Virginia University', 'lat': 39.6480359, 'long': -79.9697147}
{'college': 'Central Connecticut State University', 'lat': 41.6929529, 'long': -72.7682547}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'Marquette University', 'lat': 43.0388337, 'long': -87.92856669999999}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'Texas Tech University', 'lat': 33.5842591, 'long': -101.8782822}
{'college': 'University of Missouri', 'lat': 38.9403808, 'long': -92.32773750000001}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'Oklahoma State University', 'lat': 36.1270236, 'long': -97.07372219999999}

{'college': 'Western Kentucky University', 'lat': 36.983537, 'long': -86.4573752}
{'college': 'University of Memphis', 'lat': 35.1187498, 'long': -89.9374928}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Vanderbilt University', 'lat': 36.1447034, 'long': -86.8026551}
{'college': 'Morehead State University', 'lat': 38.1886162, 'long': -83.4315122}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Georgia Institute of Technology', 'lat': 33.7756178, 'long': -84.39628499999999}
{'college': ' University of Nevada', 'lat': 39.5441917, 'long': -119.816397}
{'college': 'Arizona State University', 'lat': 33.4242399, 'long': -111.9280527}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'Stanford University', 'lat': 37.4274745, 'long': -122.169719}
{'college': 'Stanford University', 'lat': 37.4274745, 'long': -122.169719}
{'college': 'Stanford University', 'lat': 37.4274745, 'long': -122.169719}
{'college': 'Iowa State University', 'lat': 42.0266187, 'long': -93.6464654}
{'college': ' Manhattan College', 'lat': 40.88978230000001, 'long': -73.9027188}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'University of Houston', 'lat': 29.7199489, 'long': -95.3422334}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Villanova University', 'lat': 40.0378952, 'long': -75.34333149999999}
{'college': 'Villanova University', 'lat': 40.0378952, 'long': -75.34333149999999}
{'college': 'San Diego State University', 'lat': 32.7759894, 'long': -117.0712533}
{'college': 'San Diego State University', 'lat': 32.7759894, 'long': -117.0712533}
{'college': 'San Diego State University', 'lat': 32.7759894, 'long': -117.0712533}
{'college': 'San Diego State University', 'lat': 32.7759894, 'long': -117.0712533}
{'college': 'Brigham Young University', 'lat': 40.2518435, 'long': -111.6493156}
{'college': 'Vanderbilt University', 'lat': 36.1447034, 'long': -86.8026551}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Louisville', 'lat': 38.2122761, 'long': -85.75850229999999}
{'college': 'University of Louisville', 'lat': 38.2122761, 'long': -85.75850229999999}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': ' Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'University of Southern California', 'lat': 34.0223519, 'long': -118.285117}
{'college': ' University of New Mexico', 'lat': 35.0843187, 'long': -106.6197812}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Providence College', 'lat': 41.8440925, 'long': -71.4381653}
{'college': 'Providence College', 'lat': 41.8440925, 'long': -71.4381653}
{'college': 'Providence College', 'lat': 41.8440925, 'long': -71.4381653}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'Indiana University', 'lat': 39.1754487, 'long': -86.512627}
{'college': 'College of Charleston', 'lat': 32.7834441, 'long': -79.93700179999999}
{'college': ' Oklahoma State University', 'lat': 36.1270236, 'long': -97.07372219999999}
{'college': ' University of New Mexico', 'lat': 35.0843187, 'long': -106.6197812}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'University of Notre Dame', 'lat': 41.7055716, 'long': -86.2353388}
{'college': 'University of Pittsburgh', 'lat': 40.4443533, 'long': -79.960835}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'Virginia Polytechnic Institute and State University', 'lat': 37.22838429999999, 'long': -80.42341669999999}
{'college': 'Georgetown University', 'lat': 38.9076089, 'long': -77.07225849999999}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': 'University of Detroit Mercy', 'lat': 42.4141556, 'long': -83.1379932}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': ' University of Louisiana at Lafayette', 'lat': 30.2114404, 'long': -92.0204121}
{'college': 'University of Oklahoma', 'lat': 35.2058936, 'long': -97.4457137}
{'college': 'Seton Hall University', 'lat': 40.7433773, 'long': -74.2465446}
{'college': 'University of Oklahoma', 'lat': 35.2058936, 'long': -97.4457137}
{'college': 'Indiana University', 'lat': 39.1754487, 'long': -86.512627}
{'college': 'University of Oregon', 'lat': 44.0448302, 'long': -123.0726055}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'University of Tennessee', 'lat': 35.9544013, 'long': -83.92945639999999}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': ' Louisiana State University', 'lat': 30.4132579, 'long': -91.1800023}
{'college': 'Purdue University', 'lat': 40.4237054, 'long': -86.92119459999999}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': ' Brigham Young University', 'lat': 40.2518435, 'long': -111.6493156}
{'college': 'University of Notre Dame', 'lat': 41.7055716, 'long': -86.2353388}
{'college': 'University of Michigan', 'lat': 42.2780436, 'long': -83.7382241}
{'college': 'Arizona State University', 'lat': 33.4242399, 'long': -111.9280527}
{'college': "St. John's University", 'lat': 40.7220627, 'long': -73.79421119999999}
{'college': 'University of Richmond', 'lat': 37.5751669, 'long': -77.5407146}
{'college': 'University of Louisville', 'lat': 38.2122761, 'long': -85.75850229999999}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Wisconsin', 'lat': 43.076592, 'long': -89.4124875}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'University of Virginia', 'lat': 38.0335529, 'long': -78.5079772}
{'college': 'University of Tennessee', 'lat': 35.9544013, 'long': -83.92945639999999}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Colorado', 'lat': 40.00758099999999, 'long': -105.2659417}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'Villanova University', 'lat': 40.0378952, 'long': -75.34333149999999}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': 'Austin Peay State University', 'lat': 36.53498, 'long': -87.3548855}
{'college': 'Austin Peay State University', 'lat': 36.53498, 'long': -87.3548855}
{'college': 'Austin Peay State University', 'lat': 36.53498, 'long': -87.3548855}
{'college': 'Austin Peay State University', 'lat': 36.53498, 'long': -87.3548855}
{'college': 'Austin Peay State University', 'lat': 36.53498, 'long': -87.3548855}
{'college': 'Austin Peay State University', 'lat': 36.53498, 'long': -87.3548855}
{'college': 'Indiana University', 'lat': 39.1754487, 'long': -86.512627}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': ' University of Georgia', 'lat': 33.9480053, 'long': -83.3773221}

{'college': 'Butler University', 'lat': 39.8405491, 'long': -86.1708927}
{'college': 'Marquette University', 'lat': 43.0388337, 'long': -87.92856669999999}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'University of Illinois at Urbana-Champaign', 'lat': 40.1019523, 'long': -88.2271615}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'Georgetown University', 'lat': 38.9076089, 'long': -77.07225849999999}
{'college': 'North Carolina State University', 'lat': 35.7846633, 'long': -78.6820946}
{'college': 'University of Oklahoma', 'lat': 35.2058936, 'long': -97.4457137}
{'college': 'Indiana University-Purdue University Indianapolis', 'lat': 39.7743174, 'long': -86.1764194}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of New Mexico', 'lat': 35.0843187, 'long': -106.6197812}
{'college': 'North Carolina State University', 'lat': 35.7846633, 'long': -78.6820946}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'Bowling Green State University', 'lat': 41.3797788, 'long': -83.6300826}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': ' Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': 'Arizona State University', 'lat': 33.4242399, 'long': -111.9280527}
{'college': 'Wake Forest University', 'lat': 36.1355052, 'long': -80.2791958}
{'college': 'University of Tennessee at Martin', 'lat': 36.343177, 'long': -88.86445379999999}
{'college': 'Stanford University', 'lat': 37.4274745, 'long': -122.169719}
{'college': 'Purdue University', 'lat': 40.4237054, 'long': -86.92119459999999}
{'college': ' University of Notre Dame', 'lat': 41.7055716, 'long': -86.2353388}
{'college': 'University of Minnesota', 'lat': 44.97399, 'long': -93.2277285}
{'college': 'University of Minnesota', 'lat': 44.97399, 'long': -93.2277285}
{'college': 'Ohio University', 'lat': 39.324358, 'long': -82.10138889999999}
{'college': 'DePaul University', 'lat': 41.9247559, 'long': -87.6566465}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Florida State University', 'lat': 30.4418778, 'long': -84.2984889}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'Kansas State University', 'lat': 39.1974437, 'long': -96.5847249}
{'college': 'Georgia Institute of Technology', 'lat': 33.7756178, 'long': -84.39628499999999}
{'college': 'Georgia Institute of Technology', 'lat': 33.7756178, 'long': -84.39628499999999}
{'college': 'Georgia Institute of Technology', 'lat': 33.7756178, 'long': -84.39628499999999}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'University of Oregon', 'lat': 44.0448302, 'long': -123.0726055}
{'college': 'Baylor University', 'lat': 31.5469132, 'long': -97.1210998}
{'college': 'Boston College', 'lat': 42.3355488, 'long': -71.16849450000001}
{'college': 'Stanford University', 'lat': 37.4274745, 'long': -122.169719}
{'college': 'Florida State University', 'lat': 30.4418778, 'long': -84.2984889}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'Midland College', 'lat': 32.0304457, 'long': -102.1061597}
{'college': ' California State University', 'lat': 34.0667698, 'long': -118.1684392}
{'college': 'Baylor University', 'lat': 31.5469132, 'long': -97.1210998}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'Indiana University', 'lat': 39.1754487, 'long': -86.512627}
{'college': 'Hofstra University', 'lat': 40.7166872, 'long': -73.5993965}
{'college': 'Vanderbilt University', 'lat': 36.1447034, 'long': -86.8026551}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'Florida State University', 'lat': 30.4418778, 'long': -84.2984889}
{'college': ' University of Nevada', 'lat': 39.5441917, 'long': -119.816397}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Cincinnati', 'lat': 39.1329219, 'long': -84.51495039999999}
{'college': 'Purdue University', 'lat': 40.4237054, 'long': -86.92119459999999}
{'college': 'Wake Forest University', 'lat': 36.1355052, 'long': -80.2791958}
{'college': 'University of Arkansas', 'lat': 36.0686895, 'long': -94.1748471}
{'college': 'Ohio State University', 'lat': 40.0068363, 'long': -83.0306222}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': ' Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'Marquette University', 'lat': 43.0388337, 'long': -87.92856669999999}
{'college': 'Georgia Institute of Technology', 'lat': 33.7756178, 'long': -84.39628499999999}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': ' Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Vanderbilt University', 'lat': 36.1447034, 'long': -86.8026551}
{'college': 'University of South Florida', 'lat': 28.0587031, 'long': -82.41385389999999}
{'college': 'University of Oregon', 'lat': 44.0448302, 'long': -123.0726055}
{'college': 'University of Miami', 'lat': 25.7178924, 'long': -80.2746368}
{'college': 'Baylor University', 'lat': 31.5469132, 'long': -97.1210998}
{'college': 'University of South Florida', 'lat': 28.0587031, 'long': -82.41385389999999}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Texas A&M University', 'lat': 30.6090918, 'long': -96.3337124}
{'college': 'University of Tulsa', 'lat': 36.1520526, 'long': -95.94607529999999}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'Central Michigan University', 'lat': 43.5819086, 'long': -84.7756364}
{'college': 'University of Wisconsin', 'lat': 43.076592, 'long': -89.4124875}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Missouri', 'lat': 38.9403808, 'long': -92.32773750000001}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Creighton University', 'lat': 41.2655521, 'long': -95.94638619999999}
{'college': 'Ohio State University', 'lat': 40.0068363, 'long': -83.0306222}
{'college': 'University of Utah', 'lat': 40.7649368, 'long': -111.8421021}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}

{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Purdue University', 'lat': 40.4237054, 'long': -86.92119459999999}
{'college': 'Vanderbilt University', 'lat': 36.1447034, 'long': -86.8026551}
{'college': 'University of Miami', 'lat': 25.7178924, 'long': -80.2746368}
{'college': 'University of Massachusetts Amherst', 'lat': 42.3867598, 'long': -72.5300515}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Texas A&M University', 'lat': 30.6090918, 'long': -96.3337124}
{'college': 'Georgia Institute of Technology', 'lat': 33.7756178, 'long': -84.39628499999999}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'University of Maryland', 'lat': 38.9869183, 'long': -76.9425543}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Western Kentucky University', 'lat': 36.983537, 'long': -86.4573752}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Maryland', 'lat': 38.9869183, 'long': -76.9425543}
{'college': 'San Diego State University', 'lat': 32.7759894, 'long': -117.0712533}
{'college': 'University of Illinois at Urbana-Champaign', 'lat': 40.1019523, 'long': -88.2271615}
{'college': 'University of Georgia', 'lat': 33.9480053, 'long': -83.3773221}
{'college': 'University of Wisconsin', 'lat': 43.076592, 'long': -89.4124875}
{'college': 'University of Michigan', 'lat': 42.2780436, 'long': -83.7382241}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Weber State University', 'lat': 41.19246820000001, 'long': -111.9444959}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Stanford University', 'lat': 37.4274745, 'long': -122.169719}
{'college': 'Stanford University', 'lat': 37.4274745, 'long': -122.169719}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Villanova University', 'lat': 40.0378952, 'long': -75.34333149999999}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Butler University', 'lat': 39.8405491, 'long': -86.1708927}
{'college': ' University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Stanford University', 'lat': 37.4274745, 'long': -122.169719}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Iowa', 'lat': 41.6626963, 'long': -91.5548998}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'Louisiana State University', 'lat': 30.4132579, 'long': -91.1800023}
{'college': 'University of Cincinnati', 'lat': 39.1329219, 'long': -84.51495039999999}
{'college': 'Western Carolina University', 'lat': 35.3093802, 'long': -83.18442209999999}
{'college': 'Oklahoma State University', 'lat': 36.1270236, 'long': -97.07372219999999}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Virginia', 'lat': 38.0335529, 'long': -78.5079772}
{'college': 'University of Cincinnati', 'lat': 39.1329219, 'long': -84.51495039999999}
{'college': 'University of Cincinnati', 'lat': 39.1329219, 'long': -84.51495039999999}
{'college': 'University of Cincinnati', 'lat': 39.1329219, 'long': -84.51495039999999}
{'college': 'University of Cincinnati', 'lat': 39.1329219, 'long': -84.51495039999999}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'Virginia Commonwealth University', 'lat': 37.5483122, 'long': -77.4526805}
{'college': 'University of Southern California', 'lat': 34.0223519, 'long': -118.285117}
{'college': 'University of Southern California', 'lat': 34.0223519, 'long': -118.285117}
{'college': 'University of Southern California', 'lat': 34.0223519, 'long': -118.285117}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Detroit Mercy', 'lat': 42.4141556, 'long': -83.1379932}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': ' University of Nevada', 'lat': 39.5441917, 'long': -119.816397}
{'college': 'Lehigh University', 'lat': 40.6059932, 'long': -75.3766579}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'Clemson University', 'lat': 34.6738437, 'long': -82.8368654}
{'college': 'Clemson University', 'lat': 34.6738437, 'long': -82.8368654}
{'college': 'Creighton University', 'lat': 41.2655521, 'long': -95.94638619999999}
{'college': 'University of Michigan', 'lat': 42.2780436, 'long': -83.7382241}
{'college': ' University of Nevada', 'lat': 39.5441917, 'long': -119.816397}
{'college': ' California State University', 'lat': 34.0667698, 'long': -118.1684392}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Tennessee', 'lat': 35.9544013, 'long': -83.92945639999999}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'Louisiana State University', 'lat': 30.4132579, 'long': -91.1800023}
{'college': 'Texas A&M University', 'lat': 30.6090918, 'long': -96.3337124}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': 'Baylor University', 'lat': 31.5469132, 'long': -97.1210998}
{'college': "Saint Mary's College of California", 'lat': 37.8413472, 'long': -122.1101354}
{'college': 'Louisiana Tech University', 'lat': 32.5282644, 'long': -92.6499298}
{'college': 'University of Louisville', 'lat': 38.2122761, 'long': -85.75850229999999}
{'college': 'University of North Texas', 'lat': 33.207488, 'long': -97.1525862}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Georgetown University', 'lat': 38.9076089, 'long': -77.07225849999999}
{'college': 'Purdue University', 'lat': 40.4237054, 'long': -86.92119459999999}
{'college': 'University of Michigan', 'lat': 42.2780436, 'long': -83.7382241}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Maryland', 'lat': 38.9869183, 'long': -76.9425543}
{'college': 'Gonzaga University', 'lat': 47.66703210000001, 'long': -117.4014343}
{'college': 'University of Utah', 'lat': 40.7649368, 'long': -111.8421021}
{'college': ' Mississippi State University', 'lat': 33.4551742, 'long': -88.79437659999999}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Ohio State University', 'lat': 40.0068363, 'long': -83.0306222}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': 'Tennessee Technological University', 'lat': 36.1757592, 'long': -85.5086374}
{'college': 'University of Notre Dame', 'lat': 41.7055716, 'long': -86.2353388}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}

{'college': ' Shaw University', 'lat': 35.771043, 'long': -78.6379262}
{'college': 'Bucknell University', 'lat': 40.9547722, 'long': -76.88507589999999}
{'college': 'Rutgers University', 'lat': 40.5008186, 'long': -74.44739910000001}
{'college': 'Auburn University', 'lat': 32.5933574, 'long': -85.4951663}
{'college': ' Iowa State University', 'lat': 42.0266187, 'long': -93.6464654}
{'college': 'University of Oklahoma', 'lat': 35.2058936, 'long': -97.4457137}
{'college': 'University of Wyoming', 'lat': 41.3148754, 'long': -105.5665744}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': "Saint Joseph's University", 'lat': 39.9951217, 'long': -75.23993279999999}
{'college': "Saint Joseph's University", 'lat': 39.9951217, 'long': -75.23993279999999}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'St. Bonaventure University', 'lat': 42.0794875, 'long': -78.48427029999999}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Marquette University', 'lat': 43.0388337, 'long': -87.92856669999999}
{'college': 'Louisiana State University', 'lat': 30.4132579, 'long': -91.1800023}
{'college': 'Bradley University', 'lat': 40.6977743, 'long': -89.6153484}
{'college': 'Norfolk State University', 'lat': 36.8480161, 'long': -76.262085}
{'college': 'Ohio State University', 'lat': 40.0068363, 'long': -83.0306222}
{'college': 'Southern Methodist University', 'lat': 32.8412178, 'long': -96.78451749999999}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Indiana University', 'lat': 39.1754487, 'long': -86.512627}
{'college': 'Gonzaga University', 'lat': 47.66703210000001, 'long': -117.4014343}
{'college': 'University of Louisville', 'lat': 38.2122761, 'long': -85.75850229999999}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': ' University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': 'University of Pittsburgh', 'lat': 40.4443533, 'long': -79.960835}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Creighton University', 'lat': 41.2655521, 'long': -95.94638619999999}
{'college': 'Wake Forest University', 'lat': 36.1355052, 'long': -80.2791958}
{'college': 'Murray State University', 'lat': 36.6163842, 'long': -88.3214979}
{'college': 'University of Louisiana at Lafayette', 'lat': 30.2114404, 'long': -92.0204121}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Utah', 'lat': 40.7649368, 'long': -111.8421021}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': 'Auburn University', 'lat': 32.5933574, 'long': -85.4951663}
{'college': 'Georgetown University', 'lat': 38.9076089, 'long': -77.07225849999999}
{'college': 'University of Arkansas', 'lat': 36.0686895, 'long': -94.1748471}
{'college': "St. John's University", 'lat': 40.7220627, 'long': -73.79421119999999}
{'college': 'University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Stanford University', 'lat': 37.4274745, 'long': -122.169719}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Southern California', 'lat': 34.0223519, 'long': -118.285117}
{'college': 'University of Minnesota', 'lat': 44.97399, 'long': -93.2277285}
{'college': 'University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Louisiana State University', 'lat': 30.4132579, 'long': -91.1800023}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'Ohio State University', 'lat': 40.0068363, 'long': -83.0306222}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Miami', 'lat': 25.7178924, 'long': -80.2746368}
{'college': 'University of Mississippi', 'lat': 34.3647324, 'long': -89.538443}
{'college': 'Florida State University', 'lat': 30.4418778, 'long': -84.2984889}
{'college': 'Georgia Institute of Technology', 'lat': 33.7756178, 'long': -84.39628499999999}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'University of Tennessee', 'lat': 35.9544013, 'long': -83.92945639999999}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'DePaul University', 'lat': 41.9247559, 'long': -87.6566465}
{'college': 'University of Oregon', 'lat': 44.0448302, 'long': -123.0726055}
{'college': 'University of Oregon', 'lat': 44.0448302, 'long': -123.0726055}
{'college': 'University of Oregon', 'lat': 44.0448302, 'long': -123.0726055}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Colorado', 'lat': 40.00758099999999, 'long': -105.2659417}
{'college': ' Mississippi State University', 'lat': 33.4551742, 'long': -88.79437659999999}
{'college': 'University of Michigan', 'lat': 42.2780436, 'long': -83.7382241}
{'college': 'University of Michigan', 'lat': 42.2780436, 'long': -83.7382241}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Memphis', 'lat': 35.1187498, 'long': -89.9374928}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': 'University of Louisville', 'lat': 38.2122761, 'long': -85.75850229999999}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Missouri', 'lat': 38.9403808, 'long': -92.32773750000001}
{'college': 'Ohio State University', 'lat': 40.0068363, 'long': -83.0306222}
{'college': 'Gonzaga University', 'lat': 47.66703210000001, 'long': -117.4014343}
{'college': 'Gonzaga University', 'lat': 47.66703210000001, 'long': -117.4014343}
{'college': 'University of Miami', 'lat': 25.7178924, 'long': -80.2746368}
{'college': 'University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Virginia Commonwealth University', 'lat': 37.5483122, 'long': -77.4526805}
{'college': 'Southern Methodist University', 'lat': 32.8412178, 'long': -96.78451749999999}
{'college': 'University of Cincinnati', 'lat': 39.1329219, 'long': -84.51495039999999}
{'college': 'University of Southern California', 'lat': 34.0223519, 'long': -118.285117}
{'college': 'University of Virginia', 'lat': 38.0335529, 'long': -78.5079772}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': ' University of Nevada', 'lat': 39.5441917, 'long': -119.816397}
{'college': ' University of Alabama at Birmingham', 'lat': 33.5019893, 'long': -86.8064433}
{'college': 'Georgia Institute of Technology', 'lat': 33.7756178, 'long': -84.39628499999999}

{'college': 'New Mexico State University', 'lat': 32.2787745, 'long': -106.7479059}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'Louisiana State University', 'lat': 30.4132579, 'long': -91.1800023}
{'college': 'DePaul University', 'lat': 41.9247559, 'long': -87.6566465}
{'college': 'North Carolina State University', 'lat': 35.7846633, 'long': -78.6820946}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Virginia', 'lat': 38.0335529, 'long': -78.5079772}
{'college': 'Florida State University', 'lat': 30.4418778, 'long': -84.2984889}
{'college': 'University of Louisville', 'lat': 38.2122761, 'long': -85.75850229999999}
{'college': 'Marshall University', 'lat': 38.4235252, 'long': -82.42641449999999}
{'college': 'Oklahoma State University', 'lat': 36.1270236, 'long': -97.07372219999999}
{'college': 'Boston College', 'lat': 42.3355488, 'long': -71.16849450000001}
{'college': 'Boston College', 'lat': 42.3355488, 'long': -71.16849450000001}
{'college': 'North Carolina State University', 'lat': 35.7846633, 'long': -78.6820946}
{'college': 'Southeastern Illinois College', 'lat': 37.7515069, 'long': -88.4364622}
{'college': 'Louisiana State University', 'lat': 30.4132579, 'long': -91.1800023}
{'college': 'Colorado State University', 'lat': 40.573436, 'long': -105.0865473}
{'college': 'University of Louisiana at Monroe', 'lat': 32.5267122, 'long': -92.07317909999999}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Louisville', 'lat': 38.2122761, 'long': -85.75850229999999}
{'college': 'University of Louisville', 'lat': 38.2122761, 'long': -85.75850229999999}
{'college': 'University of New Mexico', 'lat': 35.0843187, 'long': -106.6197812}
{'college': ' University of Nevada', 'lat': 39.5441917, 'long': -119.816397}
{'college': 'Clemson University', 'lat': 34.6738437, 'long': -82.8368654}
{'college': 'Wake Forest University', 'lat': 36.1355052, 'long': -80.2791958}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'University of Florida', 'lat': 29.6436325, 'long': -82.3549302}
{'college': 'University of Michigan', 'lat': 42.2780436, 'long': -83.7382241}
{'college': 'University of Cincinnati', 'lat': 39.1329219, 'long': -84.51495039999999}
{'college': 'University of Cincinnati', 'lat': 39.1329219, 'long': -84.51495039999999}
{'college': 'University of Tennessee', 'lat': 35.9544013, 'long': -83.92945639999999}
{'college': 'University of Maryland', 'lat': 38.9869183, 'long': -76.9425543}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'University of Maryland', 'lat': 38.9869183, 'long': -76.9425543}
{'college': 'Eastern Washington University', 'lat': 47.4910283, 'long': -117.5862361}
{'college': 'Eastern Washington University', 'lat': 47.4910283, 'long': -117.5862361}
{'college': 'Eastern Washington University', 'lat': 47.4910283, 'long': -117.5862361}
{'college': 'Ohio State University', 'lat': 40.0068363, 'long': -83.0306222}
{'college': 'Georgetown University', 'lat': 38.9076089, 'long': -77.07225849999999}
{'college': 'Purdue University', 'lat': 40.4237054, 'long': -86.92119459999999}
{'college': 'Georgetown University', 'lat': 38.9076089, 'long': -77.07225849999999}
{'college': 'Louisiana State University', 'lat': 30.4132579, 'long': -91.1800023}
{'college': 'University of Pittsburgh', 'lat': 40.4443533, 'long': -79.960835}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'Vanderbilt University', 'lat': 36.1447034, 'long': -86.8026551}
{'college': 'University of Central Florida', 'lat': 28.6024274, 'long': -81.2000599}
{'college': 'Iowa State University', 'lat': 42.0266187, 'long': -93.6464654}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'Wake Forest University', 'lat': 36.1355052, 'long': -80.2791958}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': 'Louisiana State University', 'lat': 30.4132579, 'long': -91.1800023}
{'college': 'University of Georgia', 'lat': 33.9480053, 'long': -83.3773221}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Rider University', 'lat': 40.2788009, 'long': -74.73798839999999}
{'college': 'Washington State University', 'lat': 46.7319225, 'long': -117.1542121}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'Florida State University', 'lat': 30.4418778, 'long': -84.2984889}
{'college': 'Louisiana State University', 'lat': 30.4132579, 'long': -91.1800023}
{'college': 'University of South Carolina', 'lat': 33.9937575, 'long': -81.0299186}
{'college': 'Iowa State University', 'lat': 42.0266187, 'long': -93.6464654}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Southern California', 'lat': 34.0223519, 'long': -118.285117}
{'college': 'University of Wisconsin', 'lat': 43.076592, 'long': -89.4124875}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': 'Gonzaga University', 'lat': 47.66703210000001, 'long': -117.4014343}
{'college': 'Ohio State University', 'lat': 40.0068363, 'long': -83.0306222}
{'college': 'University of Texas at Austin', 'lat': 30.2849185, 'long': -97.7340567}
{'college': ' Baylor University', 'lat': 31.5469132, 'long': -97.1210998}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'Michigan State University', 'lat': 42.701848, 'long': -84.4821719}
{'college': 'Mississippi State University', 'lat': 33.4551742, 'long': -88.79437659999999}
{'college': 'University of Maryland', 'lat': 38.9869183, 'long': -76.9425543}
{'college': ' University of Nevada', 'lat': 39.5441917, 'long': -119.816397}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'Indiana University', 'lat': 39.1754487, 'long': -86.512627}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'Iowa State University', 'lat': 42.0266187, 'long': -93.6464654}
{'college': 'University of Southern California', 'lat': 34.0223519, 'long': -118.285117}
{'college': 'Marquette University', 'lat': 43.0388337, 'long': -87.92856669999999}
{'college': 'Florida State University', 'lat': 30.4418778, 'long': -84.2984889}
{'college': 'University of Memphis', 'lat': 35.1187498, 'long': -89.9374928}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': 'Kansas State University', 'lat': 39.1974437, 'long': -96.5847249}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'University of Kentucky', 'lat': 38.0306511, 'long': -84.5039697}
{'college': 'University of Alabama', 'lat': 33.2140233, 'long': -87.5391418}
{'college': 'Baylor University', 'lat': 31.5469132, 'long': -97.1210998}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'North Carolina State University', 'lat': 35.7846633, 'long': -78.6820946}
{'college': 'University of Oklahoma', 'lat': 35.2058936, 'long': -97.4457137}
{'college': 'Syracuse University', 'lat': 43.0391534, 'long': -76.1351158}
{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': 'Washington State University', 'lat': 46.7319225, 'long': -117.1542121}
{'college': 'University of Arkansas', 'lat': 36.0686895, 'long': -94.1748471}
{'college': 'Xavier University', 'lat': 39.149448, 'long': -84.47363740000002}
{'college': 'Xavier University', 'lat': 39.149448, 'long': -84.47363740000002}
{'college': "Saint Joseph's University", 'lat': 39.9951217, 'long': -75.23993279999999}

{'college': ' University of California', 'lat': 37.8718992, 'long': -122.2585399}
{'college': ' University of Cincinnati', 'lat': 39.1329219, 'long': -84.51495039999999}
{'college': 'Indiana University', 'lat': 39.1754487, 'long': -86.512627}
{'college': 'University of Colorado', 'lat': 40.00758099999999, 'long': -105.2659417}
{'college': ' University of Cincinnati', 'lat': 39.1329219, 'long': -84.51495039999999}
{'college': 'University of North Carolina at Charlotte', 'lat': 35.3070929, 'long': -80.735164}
{'college': 'Iowa State University', 'lat': 42.0266187, 'long': -93.6464654}
{'college': 'Seton Hall University', 'lat': 40.7433773, 'long': -74.2465446}
{'college': 'Marshall University', 'lat': 38.4235252, 'long': -82.42641449999999}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Maryland', 'lat': 38.9869183, 'long': -76.9425543}
{'college': 'University of Illinois at Urbana-Champaign', 'lat': 40.1019523, 'long': -88.2271615}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': ' University of Memphis', 'lat': 35.1187498, 'long': -89.9374928}
{'college': 'University of Illinois at Urbana-Champaign', 'lat': 40.1019523, 'long': -88.2271615}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Maryland', 'lat': 38.9869183, 'long': -76.9425543}
{'college': 'University of Connecticut', 'lat': 41.8077414, 'long': -72.2539805}
{'college': 'University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'University of Alabama', 'lat': 33.2140233, 'long': -87.5391418}
{'college': 'Boston College', 'lat': 42.3355488, 'long': -71.16849450000001}
{'college': 'University of Memphis', 'lat': 35.1187498, 'long': -89.9374928}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Louisville', 'lat': 38.2122761, 'long': -85.75850229999999}
{'college': 'University of Michigan', 'lat': 42.2780436, 'long': -83.7382241}
{'college': 'Duke University', 'lat': 36.0014258, 'long': -78.9382286}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': ' University of Arizona', 'lat': 32.2318851, 'long': -110.9501094}
{'college': 'Northeast Mississippi Community College', 'lat': 34.667266, 'long': -88.56243599999999}
{'college': 'Texas A&M University', 'lat': 30.6090918, 'long': -96.3337124}
{'college': 'Indiana University', 'lat': 39.1754487, 'long': -86.512627}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': 'University of Utah', 'lat': 40.7649368, 'long': -111.8421021}
{'college': 'University of Kansas', 'lat': 38.9543439, 'long': -95.2557961}
{'college': 'University of Washington', 'lat': 47.6912794, 'long': -122.3176141}
{'college': ' University of Oregon', 'lat': 44.0448302, 'long': -123.0726055}
{'college': 'University of Southern California', 'lat': 34.0223519, 'long': -118.285117}
{'college': 'University of Pittsburgh', 'lat': 40.4443533, 'long': -79.960835}
{'college': 'Georgia Institute of Technology', 'lat': 33.7756178, 'long': -84.39628499999999}
{'college': 'Indiana University', 'lat': 39.1754487, 'long': -86.512627}
{'college': 'University of North Carolina', 'lat': 35.9049122, 'long': -79.0469134}
{'college': ' University of Nevada', 'lat': 39.5441917, 'long': -119.816397}

In [24]:
NewDF['college'] = NewDF.replace(" ", "")

In [25]:
NewDF.head(1000)

                             college        lat        long
0              Pepperdine University  34.041404 -118.709581
1                  Baylor University  31.546913  -97.121100
2              University of Arizona  32.231885 -110.950109
3           University of California  37.871899 -122.258540
4           University of Pittsburgh  40.444353  -79.960835
..                               ...        ...         ...
757         University of Pittsburgh  40.444353  -79.960835
758  Georgia Institute of Technology  33.775618  -84.396285
759               Indiana University  39.175449  -86.512627
760     University of North Carolina  35.904912  -79.046913
761             University of Nevada  39.544192 -119.816397

[762 rows x 3 columns]

In [26]:
merged = pd.merge(players, NewDF, left_on = 'college', right_on = 'college', how = 'left')

In [27]:
merged = merged.drop_duplicates(['player_id'], keep = "last")

In [28]:
new_position= []
for position in merged.position:
    position = position.split(" ")
    if len(position) > 1:
        position_clear = position[0] + " " + position[1]
        
    else:
        position_clear = position[0]
    new_position.append(position_clear)

In [29]:
merged['position'] = new_position
merged_duplicates = merged[merged.duplicated()]
print("Duplicate Rows except first occurrence based on all columns are :")
print(merged_duplicates)

# Select duplicate rows except first occurrence based on all columns
merged_duplicates = merged[merged.duplicated()]

Duplicate Rows except first occurrence based on all columns are :
Empty DataFrame
Columns: [player_id, birthDate, draft_year, name, position, college, salary, season_end, season_start, team, lat, long]
Index: []

In [30]:
merged['position'].replace('Center and','Center',inplace=True)

In [31]:
college_sp = merged["college"]
college_stri = []
for college in college_sp:
    college_stri.append(college.strip())

In [32]:
merged["college"] = college_stri

In [33]:
merged = merged.set_index('player_id')

In [34]:
merged = merged.dropna()

In [35]:
# Export to csv

merged.to_csv('NBAdataset.csv')

In [ ]:
# Export to json
merged.reset_index().to_json('NBAdataJSON.json', orient = 'records')

In [ ]:
# SQL upload

database_username = input('ENTER USERNAME')
database_password = input('ENTER PASSWORD')
database_name     = 'NBAdataset'
database_connection = sqlalchemy.create_engine('postgresql://{0}:{1}@localhost:5432/{2}'.format(database_username, database_password, database_name))
merged.to_sql(con=database_connection, name='NBAdataset', if_exists='append')

**----------END OF CODE----------**